### ISSUE TITLE
Use newer version of GHC to compile cardano-node

### ISSUE THREAD

**Issue by mark-stopka** [2nd-Layer/docker-hub-cardano-images#82]
`cardano-node` should be compiled with newer GHC version...

Upstream Reference: https://github.com/input-output-hk/cardano-node/issues/1484

**Comment by mark-stopka** [comment]
Upstream dependencies are now compatible with `ghc-8.10.2`, `cardano-node` itself is still pending support...

**Comment by mark-stopka** [comment]
Work in progress at full support by upstream https://github.com/input-output-hk/cardano-node/pull/1874

Test build of `master` added in 80bdfa2863b9bf7c56ac44bf196f70c858abac3e as `latest` image...

**Comment by mark-stopka** [comment]
@tiredpixel, would you not consider using Docker for your deployment? We may join forces and make easy to deploy passive relays as part of Docker Swarm cluster...

**Comment by tiredpixel** [comment]
@mark-stopka, I already use Docker-compatible containers, on a customised and optimised build—and it's open-source:
https://github.com/tiredpixel/cardano-node-docker
It does, however, differ in quite a few ways to what I've seen of 2nd Layer's.

I myself no longer use the Docker engine itself except in development, since I've moved to the whole Podman and daemonless approach for security (and sanity, given my few years with the Docker daemon)—but my image as-is should support Docker Swarm without problems, as I developed it to support that and other use-cases (it has some similarities to the Postgres-XL Docker images I wrote, which have been used for Docker Swarm, Kubernetes, and also via Helm charts: https://github.com/tiredpixel/postgres-xl-docker).

So I guess the question is which features, if any, are missing from our images? As I say, mine should support Docker Swarm already as-is; happy to accept any patches if there's any issue there. But I've designed it to support HA volumes, there, too, either off-engine (like I'm doing using things like Pacemaker and DRBD), or using one of the Docker or Kubernetes alternative storage engines.

**Comment by mark-stopka** [comment]
I would love to merge our work, if you are wiling to move to **CentOS Base** as Docker image, or we should at least write same healthcheck scripts, I may even compensate you in ADA if you were to do the work to my specification, portion of it anyway, if you would re-use the code in your images also... Your's are more oriented towards testing, mine are more production like for relays and block-producers in testing.

I plat no add support for Tor if needed to **Cardano Node** and run a testnet, so then we would also mettering scripts as part of the container.

HA is not on my priority list right now.

**Comment by tiredpixel** [comment]
@mark-stopka, I have nothing against CentOS base—I use CentOS for most of my infrastructure, and the RedHat family is my distro group of choice. But I chose Debian as the base because the official Haskell Docker images have Debian as a base, and in the past, I've run into various incompatibilities in third-party libraries when switching between OSes post-compilation.

Note I have *two* Docker image flavours, not just one—the 'build' one is indeed more orientated towards testing as you say, but the 'package' one is for production relays and block-producers. The transition between those two flavours is done by my CI robots. e.g. According to our latest 1.20.0 builds, 2nd Layer's unpacks as 517MB across 34 layers, but mine unpacks as 320MB across 14 layers.

(My build image unpacks as 3.95GB across 29 layers—but as noted, that's not for production, and it's so large purposely, since it includes all Cabal dependencies already installed, meaning it's easy to use it to test new patches or hotfix away from Cardano Node upstream.)

That means that putting those binaries into a CentOS base, or even directly into a Yum/Dnf repo should be pretty straightforward. I have healthcheck scripts, but only minimal checking the port is open; I'd like to see something checking drift against a third-party source, ideally—although that would also raise some questions.

More than happy to discuss any extensions or such for paid work, including in ADA; feel free to ping me on email with any specific ideas, and we can discuss there. :)

HA is and will remain the highest of my priorities, since it's one of my main specialisms in day-to-day work :) —so it might be interesting to see what we can take from or even merge between each other's work to get the best of both worlds. :)

**Comment by mark-stopka** [comment]
`cardano-node` latest now supports GHC 8.10.2
